// AUTO-GENERATED by scripts/sync-club-logos.ts — do not edit by hand.
// Slugs whose optimized logo lives in /public/clubs/<slug>.png (edge-served).

export const LOCAL_CLUB_LOGOS = new Set<string>([
  "aesthetrix",
  "arthaverse",
  "awc",
  "communication-design",
  "crowdcore",
  "distortion",
  "drishyakala",
  "fashion-design",
  "finwiz",
  "genesis",
  "humanique",
  "ignite",
  "interior-design",
  "jashn",
  "just-naach",
  "law-club",
  "literature",
  "mdc",
  "nexus",
  "paparazzi",
  "rotaract",
  "skribble",
  "spectrum",
  "sustainability",
  "tantra",
  "technology-club",
  "wdc",
]);

/** Local /public path for a club logo, or null if it wasn't synced. */
export function localClubLogo(slug: string): string | null {
  return LOCAL_CLUB_LOGOS.has(slug) ? `/club-logos/${slug}.png` : null;
}
