export const MEDIA_UPLOAD_MAX_BYTES = 25 * 1024 * 1024;
export const MEDIA_UPLOAD_MAX_LABEL = "25 MB";
export const CLUB_GALLERY_UPLOAD_MAX_BYTES = 4 * 1024 * 1024;
export const CLUB_GALLERY_UPLOAD_MAX_LABEL = "4 MB";

export type MediaUploadPurpose = "club-gallery";

const ALLOWED_MEDIA_TYPE = /^(image\/|video\/|application\/pdf$)/;

export function isAllowedMediaType(mimeType: string): boolean {
  return ALLOWED_MEDIA_TYPE.test(mimeType.trim().toLowerCase());
}

export function validateMediaUpload(
  input: {
    filename: string;
    mimeType: string;
    size: number;
  },
  purpose?: MediaUploadPurpose,
): string | null {
  if (!input.filename.trim()) return "The file needs a name.";
  if (!Number.isSafeInteger(input.size) || input.size <= 0) {
    return "The selected file is empty or unreadable.";
  }
  if (purpose === "club-gallery") {
    if (input.size > CLUB_GALLERY_UPLOAD_MAX_BYTES) {
      return `Club gallery photos must be under ${CLUB_GALLERY_UPLOAD_MAX_LABEL}.`;
    }
    if (!input.mimeType.trim().toLowerCase().startsWith("image/")) {
      return "Club galleries only accept image files.";
    }
    return null;
  }
  if (input.size > MEDIA_UPLOAD_MAX_BYTES) {
    return `The file is larger than ${MEDIA_UPLOAD_MAX_LABEL}.`;
  }
  if (!isAllowedMediaType(input.mimeType)) {
    return "Only images, videos, and PDF files are allowed.";
  }
  return null;
}

export function mediaUploadPurpose(
  value: unknown,
): MediaUploadPurpose | undefined {
  return value === "club-gallery" ? value : undefined;
}

/** Only accept the UUID-prefixed keys generated by makeKey(). */
export function isSafeMediaKey(key: string): boolean {
  return /^[0-9a-f-]{36}-[a-z0-9.-]{1,80}$/.test(key) && !key.includes("..");
}
