// AUTO-GENERATED by scripts/sync-recap-videos.ts — do not edit by hand.
// R2 public URLs for the recap videos. /public/recap/*.mp4 are kept in the
// repo as a Vercel edge backup; recapVideo() falls back to that path if a
// video is not in this manifest (e.g. before the script has been run).

export const RECAP_VIDEO_R2: Record<string, string> = {
  "halloween-25-recap.mp4": "https://pub-88f0a7c5d200469fa7dbb8f90c605d45.r2.dev/recap/halloween-25-recap.mp4",
  "infinity-26-aftermovie.mp4": "https://pub-88f0a7c5d200469fa7dbb8f90c605d45.r2.dev/recap/infinity-26-aftermovie.mp4",
  "infinity-26-wrap.mp4": "https://pub-88f0a7c5d200469fa7dbb8f90c605d45.r2.dev/recap/infinity-26-wrap.mp4",
  "utopia-esports.mp4": "https://pub-88f0a7c5d200469fa7dbb8f90c605d45.r2.dev/recap/utopia-esports.mp4"
};

/** R2 URL for a recap video, or the /public Vercel path as a fallback. */
export function recapVideo(filename: string): string {
  return RECAP_VIDEO_R2[filename] ?? `/recap/${filename}`;
}
