console.log("Loading payload/node...");
const { generateImportMap } = await import("payload/node");
console.log("Loading config...");
const cfg = (await import("./payload.config.ts")).default;
console.log("Awaiting cfg...");
const c = await cfg;
console.log("Generating, collections:", c.collections?.length);
await generateImportMap({ config: c, force: true, log: true });
console.log("DONE");
process.exit(0);
