/**
 * Download club logos from R2, optimize them, and write them into /public so
 * they ship with the build and are served from Vercel's edge CDN — instant,
 * cached, and (crucially) NOT routed through Vercel's image optimizer, which is
 * the metered/limited resource on the free tier.
 *
 *   npm run sync:club-logos
 *
 * Output:
 *   - public/clubs/<slug>.png   (resized ≤256px, alpha preserved)
 *   - src/lib/club-logos.ts     (generated manifest of synced slugs)
 *
 * Re-runnable. Logos are small + flat, so 27 of them total well under ~1 MB.
 */
import { config } from "dotenv";
config({ path: ".env.local" });

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { createClient } from "@libsql/client";
import sharp from "sharp";

const OUT_DIR = join(process.cwd(), "public", "club-logos");
const MANIFEST = join(process.cwd(), "src", "lib", "club-logos.ts");

async function main() {
  const db = createClient({
    url: process.env.LIBSQL_URL!,
    authToken: process.env.LIBSQL_AUTH_TOKEN,
  });

  const rows = (
    await db.execute(
      `SELECT c.slug AS slug, m.url AS url
         FROM mp_clubs c
         JOIN mp_media m ON c.logo_id = m.id
        WHERE m.url IS NOT NULL AND m.url != ''`,
    )
  ).rows as unknown as Array<{ slug: string; url: string }>;

  mkdirSync(OUT_DIR, { recursive: true });

  const synced: string[] = [];
  for (const { slug, url } of rows) {
    try {
      const res = await fetch(url);
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      const buf = Buffer.from(await res.arrayBuffer());
      await sharp(buf)
        .resize(224, 224, { fit: "inside", withoutEnlargement: true })
        // Palette PNG keeps alpha (needed for the mask), universal browser
        // support, and tiny file sizes for flat logos.
        .png({ palette: true, quality: 80, compressionLevel: 9, effort: 9 })
        .toFile(join(OUT_DIR, `${slug}.png`));
      synced.push(slug);
      console.log(`  ✓ ${slug}.png`);
    } catch (err) {
      console.warn(`  ✗ ${slug}: ${(err as Error).message} (will fall back to R2)`);
    }
  }

  synced.sort();
  const manifest = `// AUTO-GENERATED by scripts/sync-club-logos.ts — do not edit by hand.
// Slugs whose optimized logo lives in /public/clubs/<slug>.png (edge-served).

export const LOCAL_CLUB_LOGOS = new Set<string>([
${synced.map((s) => `  ${JSON.stringify(s)},`).join("\n")}
]);

/** Local /public path for a club logo, or null if it wasn't synced. */
export function localClubLogo(slug: string): string | null {
  return LOCAL_CLUB_LOGOS.has(slug) ? \`/club-logos/\${slug}.png\` : null;
}
`;
  writeFileSync(MANIFEST, manifest);

  console.log(`\n✓ Synced ${synced.length}/${rows.length} logos → public/club-logos/`);
  console.log(`✓ Wrote manifest → src/lib/club-logos.ts`);
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error("Sync failed:", err);
    process.exit(1);
  });
