/**
 * Upload the recap videos from /public/recap to Cloudflare R2 and generate a
 * manifest of their public R2 URLs.
 *
 *   npm run sync:recap-videos
 *
 * Why: the four .mp4 files in /public/recap total ~18.5 MB and autoplay on the
 * homepage vault. Served from Vercel /public they burn the free-tier bandwidth
 * quota (100 GB/mo) — one viral spike at 5000 users can exceed it in minutes.
 * R2 egress to the internet is free, so moving the videos there takes them off
 * Vercel's meter entirely while the /public copies stay as an edge-cached
 * backup (the generated `recapVideo()` falls back to `/recap/<file>` if a video
 * isn't in the manifest).
 *
 * Re-runnable. Skips files already present in R2 with the same byte size.
 */
import { config } from "dotenv";
config({ path: ".env.local" });

import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  S3Client,
  PutObjectCommand,
  HeadObjectCommand,
} from "@aws-sdk/client-s3";

const SRC_DIR = join(process.cwd(), "public", "recap");
const MANIFEST = join(process.cwd(), "src", "lib", "recap-media.ts");

async function main() {
  const base = (process.env.R2_PUBLIC_URL || "").replace(/\/$/, "");
  if (!base) throw new Error("R2_PUBLIC_URL is not set in .env.local");

  const client = new S3Client({
    region: "auto",
    endpoint: process.env.R2_ENDPOINT,
    forcePathStyle: true,
    credentials: {
      accessKeyId: process.env.R2_ACCESS_KEY_ID || "",
      secretAccessKey: process.env.R2_SECRET_ACCESS_KEY || "",
    },
  });
  const bucket = process.env.R2_BUCKET || "";
  if (!bucket) throw new Error("R2_BUCKET is not set in .env.local");

  // Only the .mp4 files are the bandwidth problem; posters (.jpg/.webp) are
  // small and fine on Vercel's edge.
  const videos = readdirSync(SRC_DIR)
    .filter((f) => f.endsWith(".mp4"))
    .sort();

  const urls: Record<string, string> = {};
  for (const file of videos) {
    const localPath = join(SRC_DIR, file);
    const size = statSync(localPath).size;
    const key = `recap/${file}`;

    // Skip upload if R2 already has the same object at the same byte size —
    // makes re-runs fast and free.
    try {
      const head = await client.send(
        new HeadObjectCommand({ Bucket: bucket, Key: key }),
      );
      if (Number(head.ContentLength) === size) {
        urls[file] = `${base}/${key}`;
        console.log(`  ✓ ${file} (already in R2, ${size} bytes)`);
        continue;
      }
    } catch {
      // Not found — fall through to upload.
    }

    const body = readFileSync(localPath);
    await client.send(
      new PutObjectCommand({
        Bucket: bucket,
        Key: key,
        Body: body,
        ContentType: "video/mp4",
      }),
    );
    urls[file] = `${base}/${key}`;
    console.log(`  ↑ ${file} uploaded (${size} bytes)`);
  }

  const manifest = `// AUTO-GENERATED by scripts/sync-recap-videos.ts — do not edit by hand.
// R2 public URLs for the recap videos. /public/recap/*.mp4 are kept in the
// repo as a Vercel edge backup; recapVideo() falls back to that path if a
// video is not in this manifest (e.g. before the script has been run).

export const RECAP_VIDEO_R2: Record<string, string> = ${
  JSON.stringify(urls, null, 2).replace(/"/g, '"')
};

/** R2 URL for a recap video, or the /public Vercel path as a fallback. */
export function recapVideo(filename: string): string {
  return RECAP_VIDEO_R2[filename] ?? \`/recap/\${filename}\`;
}
`;

  writeFileSync(MANIFEST, manifest);
  console.log(`\n✓ Uploaded/synced ${videos.length} videos → R2 recap/`);
  console.log(`✓ Wrote manifest → src/lib/recap-media.ts`);
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error("Sync failed:", err);
    process.exit(1);
  });
